name = "nuxt-cf-test-app"
compatibility_date = "2023-06-28"
account_id = "ca796fc0427365f0707f095c94dd6003"

[[kv_namespaces]]
binding = "STORAGE"
id = "d608b447885a4309955a0d028761165e"

[site]
bucket = ".output/public"

[build]
command = "NITRO_PRESET=cloudflare pnpm build"
upload.format = "service-worker"